### ISSUE TITLE
A public method to return the message amount of a message queue?

### ISSUE THREAD

**Issue by asaarashi** [empicano/aiomqtt#32]
I am building a health check API for my company's monitor service and considering taking message amount of a message queue as a health metric. Is adding a public method to return the message amount of a message queue a good idea?

Just as,
```python
    def _cb_and_generator(self, *, log_context, queue_maxsize=0):
        # Queue to hold the incoming messages
        self.messages = messages = asyncio.Queue(maxsize=queue_maxsize)
```
and
```python
        async with client.filtered_messages("#") as messages:
            await client.subscribe("#")
            async for message in messages:
                print("QUEUE SIZE", client.messages.qsize())
```

Thanks for your great works!

**Comment by frederikaalund** [comment]
Thanks for raising this issue. :+1:  Let me have a look.

Looks like this has a lot in common with #29. I guess we should do something about this queuing/back-pressure situation.

> `print("QUEUE SIZE", client.messages.qsize())`

Good idea, and I think we should do something along these lines. In practice, however, a global reference (`Client.messages`) won't do since it is possible to have multiple queues at the same time. Instead, I think we should put `qsize` on the context manager returned by `(un)filtered_messages`. E.g.:

```python
        async with client.filtered_messages("#") as messages:
            await client.subscribe("#")
            async for message in messages:
                print("QUEUE SIZE", messages.qsize())
```

**Comment by empicano** [comment]
Better late than never! You can now get the number of messages in the (client-wide) message queue with `len(client.messages)` 🙂
